App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name="App_Shop"

urlpatterns=[
    path("",views.Home.as_view(),name="home"),
    path("product-details/<pk>",views.ProductDetaits.as_view(),name="product_details"),


]

Ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('accounts/',include('App_Login.urls')),
    path('shop',include("App_Order.urls")),
    
]

urlpatterns +=staticfiles_urlpatterns()

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models

# Create your models here.

class Catergory(models.Model):
    title=models.CharField(max_length=100)
    created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural='categories'

class Product(models.Model):
    name=models.CharField(max_length=100,blank=False,null=False)
    mini_img=models.ImageField(upload_to='media/products',blank=False)
    catergory=models.ForeignKey(Catergory,on_delete=models.CASCADE,related_name='category')
    preview_text=models.TextField(max_length=150)
    details_text=models.TextField(max_length=300)
    price=models.FloatField()
    old_price=models.FloatField(default=0.00)
    created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering=['-created']

App_Shop/views.py
from django.shortcuts import render
# models
from App_Shop.models import Product
from django.contrib.auth.mixins  import LoginRequiredMixin
# class based views
from django.views.generic import ListView,DetailView

# Create your views here.

class Home(ListView):
    model=Product
    template_name='App_Shop/home.html'

class ProductDetaits(DetailView):
    model=Product
    template_name='App_Shop/product_details.html'

templates/App_Shop/home.html
{% extends 'base.html' %}

{% block body_content%}
      <!-- Banner Starts Here -->
      <div class="banner">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="caption">
                <h2>Ecommerce HTML Template</h2>
                <div class="line-dec"></div>
                <p>Pixie HTML Template can be converted into your desired CMS theme. Total <strong>5 pages</strong> included. You can use this Bootstrap v4.1.3 layout for any CMS. 
                <br><br>Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a> free template site. Thank you. Photo credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels website</a>.</p>
                <div class="main-button">
                  <a href="#">Order Now!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Banner Ends Here -->
<div class="featured-items">
    <div class="container">
      <div class="row">

        {% for product in object_list %}
        <div class="col-md-4 col-lg-3">
           
          
            <a href="{% url 'App_Shop:product_details' pk=product.pk %}">
              <div class="featured-item">
                <img src="{{product.mini_img.url}}" alt="Item 1">
                <h4>{{product.name}}</h4>
                <h6>{{product.price}}</h6>
              </div>
            </a>


  
      
         
        
        </div>
          {% endfor%}
        
        
      </div>
    </div>
  </div>


{% endblock %}

templates/App_Shop/product_details.html
{% extends 'base.html' %}

{% block body_content %}
    <!-- Single Starts Here -->
    <div class="single-product">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-heading">
                <div class="line-dec"></div>
                <h1>Single Product</h1>
              </div>
            </div>
            <div class="col-md-6">
              <div class="product-slider">
                <div id="slider" class="flexslider">
                  
                    
                      <img src="{{object.mini_img.url}}" />
                    

                    
                    <!-- items mirrored twice, total of 12 -->
                  
                </div>

              </div>
            </div>
            <div class="col-md-6">
              <div class="right-content">
                <h4>{{object.name}}</h4>
                <h6>&#2547;{{object.price}}</h6>
                <p>Proin commodo, diam a ultricies sagittis, erat odio rhoncus metus, eu feugiat lorem lacus aliquet arcu. Curabitur in gravida nisi, non placerat nibh. Praesent sit amet diam ultrices, commodo turpis id, dignissim leo. Suspendisse mauris massa, porttitor non fermentum vel, ullamcorper scelerisque velit. </p>
                <span>7 left on stock</span>
                <form action="" method="get">
                  <label for="quantity">Quantity:</label>
                  <input name="quantity" type="quantity" class="quantity-text" id="quantity" 
                      onfocus="if(this.value == '1') { this.value = ''; }" 
                      onBlur="if(this.value == '') { this.value = '1';}"
                      value="1">
                  <input type="submit" class="button" value="Order Now!">
                </form>
                <div class="down-content">
                  <div class="categories">
                    <h6>Category:{{object.catergory |upper}} </h6>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Single Page Ends Here -->
{% endblock %}