App_Login/urls.py
from django.urls import path
from App_Login import views

app_name="App_Login"

urlpatterns=[
    path('signup/',views.sign_up,name="signup"),
    path('login',views.user_login,name="user_login"),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.user_profile,name='profile'),
    
    
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name="App_Shop"

urlpatterns=[
    path("",views.Home.as_view(),name="home"),
    path("product-details/<pk>",views.ProductDetaits.as_view(),name="product_details"),


]

Ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('accounts/',include('App_Login.urls')),
    path('shop',include("App_Order.urls")),
    
]

urlpatterns +=staticfiles_urlpatterns()

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
    
        <title>{%block title_block %}My Shop{% endblock %}</title>
    
        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
    
        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
        <link rel="stylesheet" href="{%static 'assets/css/tooplate-main.css' %}">
        <link rel="stylesheet" href="{%static 'assets/css/owl.css' %}">
    <!--
    Tooplate 2114 Pixie
    https://www.tooplate.com/view/2114-pixie
    -->
      </head>
<body>
        
    <!-- Pre Header -->


    <!-- Navigation -->
    {% include 'navbar.html' %}
    <div class="message container mt-2">
        {% if messages %}
            {% for message in messages %}
            <div
             {% if message.tags%} class="alert alert-{{message.tags}}" {% endif %}
            >
                {{message}}
            </div>
            {% endfor %}
        {% endif %}

    </div>

  
      <!-- Page Content -->
      <!-- Banner Starts Here -->
      <!-- <div class="banner">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="caption">
                <h2>Ecommerce HTML Template</h2>
                <div class="line-dec"></div>
                <p>Pixie HTML Template can be converted into your desired CMS theme. Total <strong>5 pages</strong> included. You can use this Bootstrap v4.1.3 layout for any CMS. 
                <br><br>Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a> free template site. Thank you. Photo credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels website</a>.</p>
                <div class="main-button">
                  <a href="#">Order Now!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> -->
      <!-- Banner Ends Here -->
      {% block body_content %}{% endblock %}
      <!-- Featured Starts Here -->
      <!-- <div class="featured-items">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-heading">
                <div class="line-dec"></div>
                <h1>Featured Items</h1>
              </div>
            </div>
            <div class="col-md-12">
              <div class="owl-carousel owl-theme">
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-01.jpg" alt="Item 1">
                    <h4>Proin vel ligula</h4>
                    <h6>$15.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-02.jpg" alt="Item 2">
                    <h4>Erat odio rhoncus</h4>
                    <h6>$25.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-03.jpg" alt="Item 3">
                    <h4>Integer vel turpis</h4>
                    <h6>$35.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-04.jpg" alt="Item 4">
                    <h4>Sed purus quam</h4>
                    <h6>$45.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-05.jpg" alt="Item 5">
                    <h4>Morbi aliquet</h4>
                    <h6>$55.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-06.jpg" alt="Item 6">
                    <h4>Urna ac diam</h4>
                    <h6>$65.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-04.jpg" alt="Item 7">
                    <h4>Proin eget imperdiet</h4>
                    <h6>$75.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-05.jpg" alt="Item 8">
                    <h4>Nullam risus nisl</h4>
                    <h6>$85.00</h6>
                  </div>
                </a>
                <a href="single-product.html">
                  <div class="featured-item">
                    <img src="assets/images/item-06.jpg" alt="Item 9">
                    <h4>Cras tempus</h4>
                    <h6>$95.00</h6>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div> -->
      <!-- Featred Ends Here -->
  
  
      <!-- Subscribe Form Starts Here -->
      <!-- <div class="subscribe-form">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section-heading">
                <div class="line-dec"></div>
                <h1>Subscribe on PIXIE now!</h1>
              </div>
            </div>
            <div class="col-md-8 offset-md-2">
              <div class="main-content">
                <p>Integer vel turpis ultricies, lacinia ligula id, lobortis augue. Vivamus porttitor dui id dictum efficitur. Phasellus vel interdum elit.</p>
                <div class="container">
                  <form id="subscribe" action="" method="get">
                    <div class="row">
                      <div class="col-md-7">
                        <fieldset>
                          <input name="email" type="text" class="form-control" id="email" 
                          onfocus="if(this.value == 'Your Email...') { this.value = ''; }" 
                          onBlur="if(this.value == '') { this.value = 'Your Email...';}"
                          value="Your Email..." required="">
                        </fieldset>
                      </div>
                      <div class="col-md-5">
                        <fieldset>
                          <button type="submit" id="form-submit" class="button">Subscribe Now!</button>
                        </fieldset>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> -->
      <!-- Subscribe Form Ends Here -->
  
  
      
      <!-- Footer Starts Here -->
      <div class="footer">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="logo">
                <img src="assets/images/header-logo.png" alt="">
              </div>
            </div>
            <div class="col-md-12">
              <div class="footer-menu">
                <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Help</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">How It Works ?</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-12">
              <div class="social-icons">
                <ul>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                  <li><a href="#"><i class="fa fa-rss"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer Ends Here -->
  
  
      <!-- Sub Footer Starts Here -->
      <div class="sub-footer">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="copyright-text">
                <p>Copyright &copy; 2019 Company Name 
                  
                  - Design: <a rel="nofollow" href="https://www.facebook.com/tooplate">Tooplate</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Sub Footer Ends Here -->
  
  
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  
  
      <!-- Additional Scripts -->
      <script src="{% static 'assets/js/custom.js' %}"></script>
      <script src="{% static 'assets/js/owl.js' %}"></script>
  
  
      <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
      </script>
</body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="{%static 'assets/images/header-logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Shop:home' %}">Home
                        <!-- <span class="sr-only">(current)</span> -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="products.html">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">Contact Us</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav navbar-nav navbar-right">
                    <a class="nav-link" href="contact.html">Cart</a>
                </li>
                <li class="nav-item dropdown mt-2"><a class="dropdown-toggle" data-toggle="dropdown"
                        href="#">{{request.user.profile.username}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'App_Login:profile' %}">Profile</a></li>
                        <li><a href="">Orders</a></li>
                        <li><a href="{% url 'App_Login:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:user_login'%}">Login</a>
                </li>
                {% endif%}
            </ul>
        </div>
    </div>
</nav>